name: Test And Release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [8.1, 8.2, 8.3]
                release: [stable, lowest]
        
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 2
            - uses: actions/cache@v3
              with:
                path: ~/.cache/composer/files
                key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
            - uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                coverage: none
            - run: composer update --no-interaction --no-progress --prefer-dist --prefer-${{ matrix.release }}
            - run: |
                composer test

    versioning:
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: paulhatch/semantic-version@v5.2.1
              id: semver

            - name: Publish Github Release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: v${{ steps.semver.outputs.version }}
                draft: false